name: flutter_note
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  # markdown pen

  markdown: ^7.0.0
  flutter_markdown: ^0.6.14

  flutter_highlight: ^0.7.0
  highlight: ^0.7.0

  analyzer: ^6.4.1

  note:
  note_tools:
  mate:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # 应该是不需要这个东东的，暂时注释掉
#  cupertino_icons: ^1.0.2

  path: ^1.8.2
  code_builder: ^4.4.0
  file: ^7.0.0
  shared_preferences: ^2.2.2

  # flutter_inappwebview: ^6.0.0-beta.24+1  #  6.x require macos_config 13.x
#  flutter_inappwebview: ^5.7.2+3

dev_dependencies:

  test:
  flutter_test:
    sdk: flutter
   # 这俩不要貌似也没啥影响
  flutter_lints:
  lints:

  # for tools/note_dev_gen.dart
  dart_style: ^2.0.0
  glob: ^2.1.1
#dependency_overrides:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
#dependency_overrides:
#  note:
#    path: ./note
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # if app can not start , you can remove all prefix "lib/notes/*" assets , it is auto generated by note_tools
  assets:
    - note_space.json
    - lib/notes/
    - lib/notes/1.welcome/
    - lib/notes/cheetsheet/container/bar/
    - lib/notes/cheetsheet/specific/button/
    - lib/notes/cheatsheet_draft/async/
    - lib/notes/cheatsheet_draft/container_widgets/bar/
    - lib/notes/cheatsheet_draft/container_widgets/menu/
    - lib/notes/cheatsheet_draft/container_widgets/navigation/adaptive_navigation/
    - lib/notes/cheatsheet_draft/container_widgets/scrollable/Dismissible/
    - lib/notes/cheatsheet_draft/media&assets&file/assets/
    - lib/notes/cheatsheet_draft/media&assets&file/file/
    - lib/notes/cheatsheet_draft/media&assets&file/icon/
    - lib/notes/cheatsheet_draft/specific_widgets/button/ButtonStyleButton/
    - lib/notes/cheatsheet_draft/specific_widgets/button/FloatingActionButton/
    - lib/notes/cheatsheet_draft/specific_widgets/button/IconButton/
    - lib/notes/cheatsheet_draft/specific_widgets/input/
    - lib/notes/cheatsheet_draft/specific_widgets/selectable/
    - lib/notes/cheatsheet_draft/specific_widgets/slider/
    - lib/notes/cheatsheet_draft/specific_widgets/text/RichText/
    - lib/notes/cheatsheet_draft/specific_widgets/text/Text/
    - lib/notes/cheatsheet_draft/specific_widgets/webview/
    - lib/notes/cheatsheet_draft/style&theming/material3/
    - lib/notes/core_concepts/layout/
    - lib/notes/core_concepts/layout/constraints/
    - lib/notes/core_concepts/layout/old/layout/
    - lib/notes/core_concepts/navigation/
    - lib/notes/core_concepts/state/
    - lib/notes/core_concepts/state/1.vanilla_state/
    - lib/notes/core_concepts/state/StatefulBuilder/
    - lib/notes/dev/debug/
    - lib/notes/dev/devtool/
    - lib/notes/dev/devtool/vmservice/
    - lib/notes/dev/host_mirror/
    - lib/notes/dev/macos_config/
    - lib/notes/pure_dart/analyzer/
    - lib/notes/pure_dart/dart3/
    - lib/notes/pure_dart/execption/
    - lib/notes/pure_dart/serialization_json/
    - lib/notes/research/remote_view/
    - lib/notes/thinking_in_ui/readable_html_vs_dart/
    - lib/notes/z.note_inside/app_info/
    - lib/notes/z.note_inside/how_note_work/
    - lib/notes/z.note_inside/note_test_self/
    - lib/notes/z.note_inside/note_test_self/nobody/
    - lib/notes/z.note_inside/note_test_self/temp/
    - lib/notes/z.note_inside/research_parameterized_example/
    - lib/notes/Improve_app/
    - lib/notes/Improve_app/1.overview/
    - lib/notes/Improve_app/web_optimization/
    - lib/notes/core_concepts/layout/box/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages