name: you_flutter
description: "Flutter framework project, for state , navigator and other flutter development infrastructure ."
version: 0.0.6-dev.1
homepage: https://github.com/chen56/you
repository: https://github.com/chen56/you

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.12.0
  path: ^1.9.0
  you_dart: ^0.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  checks: ^0.3.0
  flutter_lints: ^3.0.2


dependency_overrides:
  #  dart CHANGELOG 3.0.0 2023-05-10
  #   - dart pub publish will no longer warn about dependency_overrides.
  #     Dependency overrides only take effect in the root package of a resolution.
  #   - ref: https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md
  you_dart:
    path: ../you_dart
