name: you_dart
description: "dart lib, for data basic tools such as json、yaml serialization ."
version: 0.0.2
homepage: https://github.com/chen56/you
repository: https://github.com/chen56/you

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
