name: you_dart
description: "dart lib, for data basic tools such as json、yaml serialization ."
version: 0.0.6-dev.2
homepage: https://github.com/chen56/you
repository: https://github.com/chen56/you

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  meta: ^1.12.0
  collection: ^1.18.0

dev_dependencies:
  test: ^1.24.0
  flutter_test:
    sdk: flutter

  checks: ^0.3.0