name: you_dart
description: "dart lib, for data basic tools such as json、yaml serialization ."
version: 0.0.6-dev.1
homepage: https://github.com/chen56/you
repository: https://github.com/chen56/you

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0
  collection: ^1.18.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  flutter_test:
    sdk: flutter

  checks: ^0.3.0