name: learn_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.3.0 <4.0.0'


# Add regular dependencies here.
dependencies:
  # https://pub.dev/packages/intl
  # Provides internationalization and localization facilities,
  # including message translation, plurals and genders,
  # date/number formatting and parsing, and bidirectional text.
  intl:
  test_api: ^0.7.0
  vm_service: ^14.2.0


dev_dependencies:
  lints:
  test:
  analyzer:
  path:
  glob:
  checks:

analyzer:
  enable-experiment:
    - annotate_redeclares

linter:
  rules:
    - annotate_redeclares
