name: note
description: A Flutter note project.
version: 1.0.0
homepage: https://github.com/chen56/note
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  meta: ^1.11.0
  collection: ^1.18.0
  path: ^1.8.3
  file: ^7.0.0

  code_builder: ^4.4.0
  dart_style: ^2.0.0
  # plugin
  args: ^2.4.2
  analyzer: ^6.4.1
  glob: ^2.1.1
  watcher: ^1.1.0
  yaml_edit: ^2.2.0
  note_dart:
    path: packages/note_dart
dev_dependencies:
  test:
