name: learn_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'


# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  note: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  lints: ^2.0.0
  test: ^1.21.0
  analyzer:
  path: ^1.8.2
  glob:

