name: flutter_web
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  markdown: ^7.0.0
  flutter_markdown: ^0.7.1

  flutter_highlight: ^0.7.0
  highlight: ^0.7.0

  analyzer: ^6.4.1

  path: ^1.8.2
  code_builder: ^4.4.0
  file: ^7.0.0
  shared_preferences: ^2.2.2
  meta: ^1.11.0
  stack_trace: ^1.11.1
  source_map_stack_trace: ^2.1.1
  http: ^1.2.1
  source_maps: ^0.10.12

  # you_*
  you_dart: ^0.0.4
  you_flutter: ^0.0.4
  you_note_dart: ^0.0.4

dev_dependencies:

  test:
  flutter_test:
    sdk: flutter
   # 这俩不要貌似也没啥影响
  flutter_lints:
  lints:

  # for tools/note_dev_gen.dart
  dart_style: ^2.0.0
  glob: ^2.1.1
#dependency_overrides:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
#dependency_overrides:
#  note:
#    path: ./note
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # if app can not start , you can remove all prefix "lib/pages/*" assets , it is auto generated by note_tools
  assets:
    [lib/pages/notes/, lib/pages/notes/Improve_app/, lib/pages/notes/Improve_app/1.overview/, lib/pages/notes/Improve_app/RepaintBoundary/, lib/pages/notes/Improve_app/event&listener&lifeycle/, lib/pages/notes/Improve_app/web_optimization/, lib/pages/notes/dev/debug/, lib/pages/notes/dev/devtool/, lib/pages/notes/dev/devtool/vmservice/, lib/pages/notes/dev/host_mirror/, lib/pages/notes/dev/macos_config/, lib/pages/notes/env_info/, lib/pages/notes/i18n/, lib/pages/notes/layout/, lib/pages/notes/layout/box_layout/constraints/, lib/pages/notes/layout/old/layout/, lib/pages/notes/layout/responsive_design/, lib/pages/notes/media&assets&file/assets/, lib/pages/notes/media&assets&file/file_desktop/, lib/pages/notes/media&assets&file/file_web/, lib/pages/notes/navigation/, lib/pages/notes/pure_dart/analyzer/, lib/pages/notes/pure_dart/async/, lib/pages/notes/pure_dart/dart3/, lib/pages/notes/pure_dart/execption/, lib/pages/notes/pure_dart/safe_interface/, lib/pages/notes/pure_dart/serialization_json/, lib/pages/notes/research/remote_view/, lib/pages/notes/research/research_parameterized_example/, lib/pages/notes/state/, lib/pages/notes/state/1.vanilla_state/, lib/pages/notes/state/StatefulBuilder/, lib/pages/notes/style&theming/material3/, lib/pages/notes/thinking_in_ui/readable_html_vs_dart/, lib/pages/notes/widgets/container_widgets/bar/, lib/pages/notes/widgets/container_widgets/menu/, lib/pages/notes/widgets/container_widgets/scrollable/Dismissible/, lib/pages/notes/widgets/specific_widgets/button/ButtonStyleButton/, lib/pages/notes/widgets/specific_widgets/button/FloatingActionButton/, lib/pages/notes/widgets/specific_widgets/button/IconButton/, lib/pages/notes/widgets/specific_widgets/button/overview/, lib/pages/notes/widgets/specific_widgets/icon/, lib/pages/notes/widgets/specific_widgets/input/, lib/pages/notes/widgets/specific_widgets/selectable/, lib/pages/notes/widgets/specific_widgets/slider/, lib/pages/notes/widgets/specific_widgets/text/RichText/, lib/pages/notes/widgets/specific_widgets/text/Text/, lib/pages/notes/widgets/specific_widgets/webview/, lib/pages/notes/x.note_inside/1.welcome/, lib/pages/notes/x.note_inside/how_note_work/, lib/pages/notes/x.note_inside/mockup_content/, lib/pages/notes/x.note_inside/note_test_self/, lib/pages/notes/x.note_inside/note_test_self/nobody/]

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

dependency_overrides:
    #  dart CHANGELOG 3.0.0 2023-05-10
    #   - dart pub publish will no longer warn about dependency_overrides.
    #     Dependency overrides only take effect in the root package of a resolution.
    #   - ref: https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md
  you_dart:
    path: ../../packages/you_dart
  you_note_dart:
    path: ../../packages/you_note_dart
  you_flutter:
    path: ../../packages/you_flutter
