name: flutter_web
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'


dependencies:
  flutter:
    sdk: flutter

  markdown: ^7.0.0
  flutter_markdown: ^0.7.1

  flutter_highlight: ^0.7.0
  highlight: ^0.7.0

  url_launcher: ^6.2.6

  analyzer: ^6.4.1

  path: ^1.8.2
  code_builder: ^4.4.0
  file: ^7.0.0
  shared_preferences: ^2.2.2
  meta: ^1.12.0
  stack_trace: ^1.11.1
  source_map_stack_trace: ^2.1.1
  http: ^1.2.1
  source_maps: ^0.10.12

  # you_*
  _you_dart_internal: ^0.0.6-dev.3
  you_dart: ^0.0.4
  you_flutter: ^0.0.4
  flutter_staggered_grid_view: ^0.7.0


dev_dependencies:

  test:
  flutter_test:
    sdk: flutter
   # 这俩不要貌似也没啥影响
  flutter_lints:
  lints:

  # for tools/note_dev_gen.dart
  dart_style: ^2.0.0
  glob: ^2.1.1
#dependency_overrides:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
#dependency_overrides:
#  note:
#    path: ./note
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # if app can not start , you can remove all prefix "lib/routes/*" assets , it is auto generated by note_tools
  assets:
    - lib/routes/page.dart
    - lib/routes/
    - lib/routes/notes/
    - lib/routes/notes/research/
    - lib/routes/notes/research/bash_note/
    - lib/routes/notes/research/parameterized/
    - lib/routes/notes/research/remote_view/
    - lib/routes/notes/layout/
    - lib/routes/notes/layout/constraints/
    - lib/routes/notes/layout/get_size/
    - lib/routes/notes/navigation/
    - lib/routes/notes/navigation/navigator_v1/
    - lib/routes/notes/navigation/navigator_v2/
    - lib/routes/notes/state/
    - lib/routes/notes/state/1.vanilla_state/
    - lib/routes/notes/state/StatefulBuilder/
    - lib/routes/notes/media&assets&file/
    - lib/routes/notes/media&assets&file/file_desktop/
    - lib/routes/notes/media&assets&file/file_web/
    - lib/routes/notes/media&assets&file/assets/
    - lib/routes/notes/material3/
    - lib/routes/notes/pure_dart/
    - lib/routes/notes/pure_dart/dart3/
    - lib/routes/notes/pure_dart/async/
    - lib/routes/notes/pure_dart/safe_interface/
    - lib/routes/notes/pure_dart/serialization_json/
    - lib/routes/notes/pure_dart/analyzer/
    - lib/routes/notes/dev/
    - lib/routes/notes/dev/host_mirror/
    - lib/routes/notes/dev/macos_config/
    - lib/routes/notes/dev/devtool/
    - lib/routes/notes/dev/devtool/vmservice/
    - lib/routes/notes/dev/debug/
    - lib/routes/notes/cheatsheets/
    - lib/routes/notes/cheatsheets/color_roles/
    - lib/routes/notes/cheatsheets/widgets/
    - lib/routes/notes/thinking_in_ui/
    - lib/routes/notes/thinking_in_ui/readable_html_vs_dart/
    - lib/routes/notes/x.note_inside/
    - lib/routes/notes/x.note_inside/how_note_work/
    - lib/routes/notes/x.note_inside/note_api_thinking/
    - lib/routes/notes/x.note_inside/mockup_content/
    - lib/routes/notes/x.note_inside/1.welcome/
    - lib/routes/notes/x.note_inside/note_test_self/
    - lib/routes/notes/x.note_inside/note_test_self/nobody/
    - lib/routes/notes/widgets/
    - lib/routes/notes/widgets/specific_widgets/
    - lib/routes/notes/widgets/specific_widgets/button/
    - lib/routes/notes/widgets/container_widgets/
    - lib/routes/notes/widgets/container_widgets/drawer/
    - lib/routes/notes/widgets/container_widgets/Card/
    - lib/routes/notes/widgets/container_widgets/app/
    - lib/routes/notes/widgets/container_widgets/dialog/
    - lib/routes/notes/widgets/container_widgets/menu/
    - lib/routes/notes/widgets/container_widgets/scrollable/
    - lib/routes/notes/widgets/container_widgets/scrollable/Dismissible/
    - lib/routes/notes/widgets/container_widgets/scrollable/DraggableScrollableSheet/
    - lib/routes/notes/widgets/container_widgets/page_view/
    - lib/routes/notes/widgets/container_widgets/bar/
    - lib/routes/notes/Improve_app/
    - lib/routes/notes/Improve_app/env_info/
    - lib/routes/notes/Improve_app/1.overview/
    - lib/routes/notes/Improve_app/error_handle/
    - lib/routes/notes/Improve_app/web_optimization/
    - lib/routes/notes/Improve_app/RepaintBoundary/
    - lib/routes/notes/Improve_app/event&listener&lifeycle/
    - lib/routes/notes/Improve_app/i18n/
    - lib/routes/notes/pure_dart/exception/
    - lib/routes/notes/cheatsheets/widgets/_examples/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

dependency_overrides:
    #  dart CHANGELOG 3.0.0 2023-05-10
    #   - dart pub publish will no longer warn about dependency_overrides.
    #     Dependency overrides only take effect in the root package of a resolution.
    #   - ref: https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md
  _you_dart_internal:
    path: ../../packages/_you_dart_internal
  you_dart:
    path: ../../packages/you_dart
  you_flutter:
    path: ../../packages/you_flutter
