name: you_note_dart
description: A Flutter note project.
version: 0.0.6-dev.1
homepage: https://github.com/chen56/note

environment:
  sdk: '>=3.4.0-282.2.beta <4.0.0'
  flutter: ">=3.22.0-0.2.pre"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.11.0
  collection: ^1.18.0
  path: ^1.8.3
  file: ^7.0.0
  http: ^1.2.1
  glob: ^2.1.1

  # content
  markdown: ^7.0.0
  highlight: ^0.7.0

  # code analyzer
  analyzer: ^6.4.1
  code_builder: ^4.4.0
  dart_style: ^2.0.0
  stack_trace: ^1.11.1
  source_map_stack_trace: ^2.1.1
  source_maps: ^0.10.12

  # plugin
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.7.1
  flutter_highlight: ^0.7.0

  # you_*
  you_dart: ^0.0.4
  you_flutter: ^0.0.4

#  async: ^2.11.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

  # for NoteDevTool
  checks: ^0.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
dependency_overrides:
  #  dart CHANGELOG 3.0.0 2023-05-10
  #   - dart pub publish will no longer warn about dependency_overrides.
  #     Dependency overrides only take effect in the root package of a resolution.
  #   - ref: https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md
  you_dart:
    path: ../you_dart
  you_flutter:
    path: ../you_flutter
