name: _you_dart_internal
description: "internal dart lib."
version: 0.0.6-dev.3
homepage: https://github.com/chen56/you
repository: https://github.com/chen56/you

environment:
  sdk: '>=3.4.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  code_builder: ^4.10.0
  collection: ^1.18.0
  file: ^7.0.0

  # flutter 3.22.0 pin `mate: 1.12.0` and analyzer 6.4.1 dep mate 1.12
  analyzer: ^6.4.1
  meta: 1.12.0

  path: ^1.9.0
  yaml: ^3.1.2
  yaml_edit: ^2.2.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  checks: ^0.3.0
