name: _you_dart_internal
description: "internal dart lib."
version: 0.0.6-dev.3
homepage: https://github.com/chen56/you
repository: https://github.com/chen56/you

environment:
  sdk: '>=3.4.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  meta: ^1.12.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  checks: ^0.3.0
