name: mate
description: mate.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  # markdown pen

  markdown: ^7.0.0
  flutter_markdown: ^0.6.14

  flutter_highlight: ^0.7.0
  highlight: ^0.7.0

  analyzer: ^5.10.0

  note:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # 应该是不需要这个东东的，暂时注释掉
  cupertino_icons: ^1.0.2

  path: ^1.8.2
  code_builder: ^4.4.0
  file: ^6.1.4
  shared_preferences: ^2.1.1

dev_dependencies:

  test:
  flutter_test:
    sdk: flutter
   # 这俩不要貌似也没啥影响
  flutter_lints: ^2.0.1
  lints: ^2.0.1

  # for tools/note_dev_gen.dart
  dart_style: ^2.0.0
  glob: ^2.1.1
