name: learn_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'


# Add regular dependencies here.
dependencies:
  # https://pub.dev/packages/intl
  # Provides internationalization and localization facilities,
  # including message translation, plurals and genders,
  # date/number formatting and parsing, and bidirectional text.
  file: ^7.0.0
  intl:
  test_api: ^0.7.0
  vm_service: ^14.2.0
  yaml: ^3.1.2
  yaml_edit: ^2.2.1


dev_dependencies:
  lints:
  test:
  analyzer:
  path:
  glob:
  checks:

analyzer:
  enable-experiment:
    - annotate_redeclares

linter:
  rules:
    - annotate_redeclares
