name: _you_flutter
description: "you_* internal package."
version: 0.0.6-dev.2
homepage: https://github.com/chen56/you
repository: https://github.com/chen56/you

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  checks: ^0.3.0
  flutter:
    sdk: flutter
  meta: ^1.12.0
  you_flutter: ^0.0.6-dev.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

dependency_overrides:
  #  dart CHANGELOG 3.0.0 2023-05-10
  #   - dart pub publish will no longer warn about dependency_overrides.
  #     Dependency overrides only take effect in the root package of a resolution.
  #   - ref: https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md
  you_dart:
    path: ../you_dart
  you_flutter:
    path: ../you_flutter
