# except main branch, other branch is issue branch , only run ci ,don't deploy.

name: other_branch.yml

on:
  push:
    branches: [ "**","!main"]
  pull_request:
    branches: [ "**","!main"  ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Flutter action
        # You may pin to the exact commit or the version.
        # uses: subosito/flutter-action@dbf1fa04f4d2e52c33185153d06cdb5443aa189d
        # https://github.com/subosito/flutter-action
        uses: subosito/flutter-action@v2.8.0
        with:
          # The Flutter version to make available on the path
          #flutter-version: # optional, default is any
          # The Flutter build release channel
          channel: beta # optional, default is stable
#          flutter-version: '3.9.0-1.0.pre.2'
          # Cache the Flutter SDK
          cache: true # optional
          # Identifier for the Flutter SDK cache
          # cache-key: # optional, default is flutter-:os:-:channel:-:version:-:arch:-:hash:
          # Flutter SDK cache path
          # cache-path: # optional, default is ${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:
          # The architecture of Flutter SDK executable (x64 or arm64)
          # architecture: # optional, default is ${{ runner.arch }}        

      - name: checkout
        uses: actions/checkout@v3

      # build
      - run: flutter --version
      - run: ./bake get
      - run: ./bake test
      - run: ./bake build
